// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Crime, CrimeData, CrimeTableId } from "./tables/Crime.sol";
import { Game, GameData, GameTableId } from "./tables/Game.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
