// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICrimeSystem {
  function create(string memory name, uint32 year, string memory description) external returns (bytes32);
}
