// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGameSystem {
  function create(bytes32 crime) external returns (bytes32);

  function endGame(bytes32 gameId, bool isGuilty) external;
}
